### ISSUE TITLE
Gabriel Barney: 1-1

### ISSUE THREAD

**Issue by gabrielvbarney** [CSC307-W2020-Team6/307-Sec01-Team6#24]
## Am I blocked?
- Not at the moment, however I believe there will be occasions where this happens when we begin developing the software.
## What I did.
- Worked with my team in creating issues to be solved in future sprints, as well as did research to get the ball rolling on our project, Lynk Up! Also, I familiarized myself with the GitHub interface.
## What I plan to do next week.
- I will continue to plan future sprints and to make changes to current issues as necessary. I will also be implementing this work item: https://github.com/MJaojoco/307-Sec01-Team6/issues/21

**Comment by gabrielvbarney** [comment]
## Am I blocked?
- Somewhat, this week did not necessarily go as planned. We underestimated the workload of each work item and learning each program would more of a hassle than we originally expected. Also, we changed the database that we are using from Firebase to MySQL because it is more compatible with Django (backend). With that being said, I am currently in the works of figuring out MySQL.
## What I did.
- Originally I created a database with Firebase. But as we started to develop parts of the backend, it became apparent that we should be using MySQL. I have started the process of learning this program.
## What I plan to do next week.
- I intend to learn SQL, and have a database up and running. As other features of our project are implemented, I will integrate our database to fit within the other parts of the code base.

**Comment by gabrielvbarney** [comment]
## Am I blocked?
- Somewhat, I have implemented a database that I am able to insert and retrieve values from. However, I am waiting to be able to grab input from the login/signup screen, which will not be achievable until the creation of this page is finished. Also, I have the database on my local machine, which will render it difficult to be accessed by my partners (Riley and Matt). I will be asking for assistance with this tomorrow in class.

## What I did.
- I implemented a SQLite Database that I have successfully been able to insert and retrieve values from. While I wait for the login/signup screen creation, I am experimenting with different ways of how to store other information about a user besides their username and password. This includes calendar settings, friends, and groups.

## What I plan to do next week.
- Myself, as well as my group members, plan to put in overtime this week to catch up to the point of where we should be now. Due to the changes to our stack, we are a bit behind where we should be. However this should not be a problem. Personally, I am going to continue to build our database to store information about the user (other than username and password, as listed above), as well as figuring out how to put the database on a remote server so that my partners are also able to access it.

**Comment by gabrielvbarney** [comment]
## Am I Blocked?
- No, things are beginning to come together and even though it seems as if we have failed a lot, we now have a streamlined approach to how we are going to complete this program. I am developing now without any major roadblocks.

## What I did.
- I began to speak with our SQLite Database using Django, where I originally was not. I am now implementing all database operations using this framework and have done a majority of the necessary things for our database's baseline functionality (No added friends/groups or Calendar settings yet). I also wrote various tests to test the functionality of certain methods and control flow of our program.
- Work items I worked on and/or completed:
  - https://github.com/MJaojoco/307-Sec01-Team6/issues/21
  - https://github.com/MJaojoco/307-Sec01-Team6/issues/18
  - https://github.com/MJaojoco/307-Sec01-Team6/issues/16
  - https://github.com/MJaojoco/307-Sec01-Team6/issues/19
  -  https://github.com/MJaojoco/307-Sec01-Team6/issues/12

## What I plan to do next week
- As more of our work items/features are implemented, I will integrate them to work with our database. This includes calendar settings, as well as added friends/groups. I plan to do this tomorrow (Monday 2/17). I also plan to write more tests as I implement new methods.

**Comment by gabrielvbarney** [comment]
## Am I Blocked?
- No, my team members and I are now making very steady progress. 

## What I did.
- I implemented the backend necessary to support what we currently have in our program. This includes the ability to log-in, register users, and navigate the pages within our program. All group members did this somewhat simultaneously since we are a bit behind. I also did a bit of front-end work to format our pages.

## What I plan to do next week.
- I plan to implement a way to save user weekly calendar settings to our database, which then projects respective unavailable times to the other users in the person's group. I will also write additional tests to cover these new methods.

**Comment by gabrielvbarney** [comment]
## Am I Blocked?
- No, my team members and I are continuing to make steady progress.

## What I did.
- I continued to research and develop the backend necessary to implement certain features of our project. This includes user input which translates to an output displaying weekly availabilities, as well as the users ability to make groups out of their added friends to share these availabilities with.
**Edit**
Links To Work Items:
- https://github.com/MJaojoco/307-Sec01-Team6/issues/48
- https://github.com/MJaojoco/307-Sec01-Team6/issues/12

## What I plan to do next week.
- I plan to finish up the backend necessary to complete this program. I will also attempt to help with the frontend implementation to fully complete this program.

**Comment by saraford** [comment]
I need to see a link to the Work Items (or Spikes) for "What I did" in order to receive credit for this lab. Please update and then send me email when you want me to regrade.

**Comment by gabrielvbarney** [comment]
##Am I Blocked?
- No, my team members and I are continuing to make steady progress.

##What I did.
- I continued to work on my assigned work items, and ran experimental tests to see how well are implementations do against certain inputs. Various work items that I have finished or that I am currently working on are linked below:
- https://github.com/CSC307-W2020-Team6/307-Sec01-Team6/issues/56
- https://github.com/CSC307-W2020-Team6/307-Sec01-Team6/issues/57
- https://github.com/CSC307-W2020-Team6/307-Sec01-Team6/issues/12
- https://github.com/CSC307-W2020-Team6/307-Sec01-Team6/issues/59
- https://github.com/CSC307-W2020-Team6/307-Sec01-Team6/issues/48

##What I plan to do next week.
- As the quarter comes to a close, so does our work on this project. I plan to finish my assigned work items and to test them before Friday so that we are able to truly say that we are proud of the program that we have created.
