### ISSUE TITLE
Matthew Jaojoco: 1-1

### ISSUE THREAD

**Issue by MJaojoco** [CSC307-W2020-Team6/307-Sec01-Team6#28]
- **Am I Blocked?:**  
No. I could reach a block soon though, as I need to learn more about UI/UX and front-end development in order to finish my current work item. 

- **What I did:** 
This week I became more comfortable on Github as I worked with my team to create the projects and issues which will serve as this week's deliverable. As a team, we decided on what frameworks we will be using for this project. We came up with three features for our MVP. I have also taken on the work item of dealing with front-end development which I am not experienced in so I have begun to  research good starting resources for front-end development, keeping in mind that I will be working with the AngularJS framework. 

- **What I plan to do next week:**
Next week I plan on expanding my skills in front-end development. I currently have the work task of designing the basic login/sign up screen that will be presented to anonymous users. I also anticipate helping with the other work items in order to stay informed on the back-end progress and learn more about databases.

**Comment by MJaojoco** [comment]
- **Am I Blocked?:**  
Not currently

- **What I did:** 
This week I downloaded Angular JS and Brackets onto my personal computer to begin developing front-end when I get familiar enough with HTML/JS and the Angular framework. I have started to use online videos to learn more about front-end development. 

- **What I plan to do next week:**
Next week I plan on doing some basic online courses to continue developing my skills in HTML/JS. I also plan on collaborating with my groupmates in order to learn more about our data base since we are switching off of Firebase.

**Comment by MJaojoco** [comment]
- **Am I Blocked?:**  
No

- **What I did:** 
I learned about HTML/CSS enough to finish a prototype for a sign up/log in page for our website with a landing page as well. These pages are very rough and are not functional yet, only aesthetic. I looked into the differences between Angular and React, and chose to move forward using React since it has less built in, I can choose what libraries are necessary rather than having to use the entire Angular framework. 

- **What I plan to do next week:**
Learn more about React and start to implement functionality to our website. I will also work with my teammates next week in order to get our database set up.

**Comment by MJaojoco** [comment]
- **Am I Blocked?:**  
No

- **What I did:** 
My group decided to go forward using Django as an end-to-end framework so I have been catching up and have familiarized myself with Django. I started writing tests that ensure functionality of the features we have been working on. 

- **What I plan to do next week:**
Next week I will work with my group mates to finish work items for the next sprint. I plan to incorporate Bootstrap into the project and this week will work on figuring out how to apply the HTML/React knowledge I have been acquiring to our new Stack in Django

**Comment by MJaojoco** [comment]
- **Am I Blocked?:**  
No

- **What I did:** 
Used Django to get a basic site working where users can create a profile and edit that profile after creation. The user can then use their credentials to log in and out of our site. Much of our page formatting using Django's built in templates but I was able to make small adjustments using CSS. Our project imports Bootstrap but does not yet implement it. 

- **What I plan to do next week:**
Next week I will continue to work on new features for our site, testing incrementally. I will also do my best to manage our branches on git and ensure that all pull requests get merged into our default branch throughout the week.

**Comment by MJaojoco** [comment]
- **Am I Blocked?:**  
No

- **What I did:**
Learned how to use Bootstrap and using Bootstrap's built in templates, redesigned our website by defining classes on certain tags in our html code. Thanks to accomplishing this, https://github.com/MJaojoco/307-Sec01-Team6/issues/49 became much easier to finish as the styling in our CSS file is minimal. Learning Bootstrap was also was useful for formatting the views associated with a new model, Post, that I helped create this week. https://github.com/MJaojoco/307-Sec01-Team6/issues/52. I also looked into different public Django apps that can be compatible with our code such as django-friendship and django-scheduler. 

- **What I plan to do next week:**
Next week I will hopefully implement the two external apps into our project, potentially with additional apps if I find more apps that will help us implement our features. https://github.com/MJaojoco/307-Sec01-Team6/issues/12 https://github.com/MJaojoco/307-Sec01-Team6/issues/14. I also plan on creating another model for our project: Group. https://github.com/MJaojoco/307-Sec01-Team6/issues/18

**Comment by saraford** [comment]
I need to see a link to the Work Items (or Spikes) for "What I did" in order to receive credit for this lab. Please update and then send me email when you want me to regrade.

**Comment by MJaojoco** [comment]
- **Am I Blocked?:**  
No

- **What I did:** 
I created a Group model that includes a Group owner and multiple members. I adjusted the project to account for this. The previous work we did with Posts has been moved into the group pages, so our home page is currently blank. 
https://github.com/MJaojoco/307-Sec01-Team6/issues/18
https://github.com/MJaojoco/307-Sec01-Team6/issues/44
https://github.com/MJaojoco/307-Sec01-Team6/issues/45
https://github.com/MJaojoco/307-Sec01-Team6/issues/46
https://github.com/MJaojoco/307-Sec01-Team6/issues/50
https://github.com/MJaojoco/307-Sec01-Team6/issues/51
I also created a .gitignore with Gabe in order to make merging branches easier. 
https://github.com/MJaojoco/307-Sec01-Team6/issues/56

- **What I plan to do next week:**
Next week I plan on assisting with the implementation with friends and getting progress on inputting schedules. I also will fix the home page of our site. 
https://github.com/MJaojoco/307-Sec01-Team6/issues/60
https://github.com/MJaojoco/307-Sec01-Team6/issues/14
https://github.com/MJaojoco/307-Sec01-Team6/issues/59
