### ISSUE TITLE
Storyboards

### ISSUE THREAD

**Issue by gabrielvbarney** [CSC307-W2020-Team6/307-Sec01-Team6#33]
Working Calendar Interface:
![working_calendar_interface](https://user-images.githubusercontent.com/33734889/73614517-b1583800-45b4-11ea-9146-87d286d2212f.jpg)

Adding Friends:
![adding_friends](https://user-images.githubusercontent.com/33734889/73614524-b9b07300-45b4-11ea-9f5d-f04de1909f9b.jpg)

Account Creation:
![account_creation](https://user-images.githubusercontent.com/33734889/73614528-cb921600-45b4-11ea-9965-77165457e4b0.jpg)

**Comment by saraford** [comment]
Your storyboards are outstanding. +5 points
