### ISSUE TITLE
Acceptance Tests: Account Creation

### ISSUE THREAD

**Issue by gabrielvbarney** [CSC307-W2020-Team6/307-Sec01-Team6#38]
## Acceptance Test for [Account Creation](https://github.com/MJaojoco/307-Sec01-Team6/issues/26 ) User Story
- Verify user can perform all CRUD operations at random locations.
- Verify user is able to navigate to the LyncUp homepage.
- Verify user is able to navigate to the "sign-up" page via the button on the LyncUp homepage.
- Verify user's account is created after entering credentials into text boxes by hitting "sign-up" button. This is checked by inspecting the database.
- Verify that after a user is signed up, they are taken to the blank calendar interface page.
- Verify that a new user is able to log out using the "log out" button.
- Verify that the recently signed-up user's status is changed from anonymous user to registered user by the ability to log back into LyncUp using their respective credentials.

**Comment by saraford** [comment]
:+1:
