### ISSUE TITLE
5. Success Metrics

### ISSUE THREAD

**Issue by MJaojoco** [CSC307-W2020-Team6/307-Sec01-Team6#5]
We will consider ourselves successful if we have an mvp that meets all of the goals and functionalities we have planned. We hope to collect tester feedback on our product at its completion and will base our success on those results. We do not plan on releasing our product to the market so we will not be able to base our success on downloads, however we could poll our testers on if they would be use the app in their personal lives.

**Comment by saraford** [comment]
success metrics here are not based on measuring your grades in this course, but what would you measure if you were to go-live. If a recruiter asked you in a phone screen to define success metrics for a MVP or feature, what would you say? List those (wrt your project) here.

**Comment by MJaojoco** [comment]
Our MVP's success would be measured by software tester comments and feedback from early users. In general, success will be attained if all the intended features for the MVP work properly. For quantitative analysis, we could see how often the average user is in the app and view a connected user graph similar to the one facebook uses for its users. This can assure us that users are interacting with our website.
