### ISSUE TITLE
6. Users - who are your 3 types of users? What features will they use?

### ISSUE THREAD

**Issue by rmete** [CSC307-W2020-Team6/307-Sec01-Team6#6]
1. Anonymous 
    * Presented with a login/sign-up page 

2. Regular
    * The ability to create groups 
           * The user will be able to add and remove members from a group that they create
    * The ability to see their friends'/associates' availability. 

3. Admin
    * See all groups made
    * The ability to remove members from any group

**Comment by saraford** [comment]
Think more about consumer versus producer types of roles. You're very close, but why have an admin at all when the regular user can do it all? Think more about a 3rd type of user.

**Comment by gabrielvbarney** [comment]
(Changing User #3)
3. Developer
     * Sees what the user sees, but with extra insight (Source Code/Consumer Data).
     * Has the power to make changes to the application itself.
