### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by MJaojoco** [CSC307-W2020-Team6/307-Sec01-Team6#9]
# [Firebase](https://firebase.google.com/?gclid=CjwKCAiAjrXxBRAPEiwAiM3DQkzr07flVMX3-2Y2q9iyDWi1yAkW_cr5tw9JLwoyXtqQkvuqYSehNBoCSp0QAvD_BwE)
Rather than setting up our own server to store user data, we will use Firebase as our real-time database

### Helpful Links:

- [Documentation](https://firebase.google.com/docs)
- [Firebase GitHub ](https://github.com/firebase/)

**Comment by gabrielvbarney** [comment]
Helpful Link: https://medium.com/google-cloud/building-a-flask-python-crud-api-with-cloud-firestore-firebase-and-deploying-on-cloud-run-29a10c502877

**Comment by gabrielvbarney** [comment]
Now using SQLite.
